### PR TITLE
Initial Raffle Spike

### PR DESCRIPTION
**Pull request by oOCKYOo**
Added the auto-loader that pulls in everything in the commands folder.
Folders are expected to contain an index.js file for the command with
all other files being subcommands.

### CODE REVIEW

**Comment by oOCKYOo** [comment]
Yeah sure. I usually have it styled with the airbnb config. Haven't bothered with it much since its been mostly just a playground to see whats possible.

Style away =)

**Comment by oOCKYOo** [comment]
Cleaned up the formatting like you asked quite a bit. Did another pass on bot.js and introduced the guilds command as a start for users to pick a guild they want to send commands for.

**Comment by oOCKYOo** [comment]
I think this would probably be the stopping point for the moment. We should look at styling and other tooling before refining and adding beyond the raffle first.

**Comment by omni5cience** [comment]
Sorry I haven't been more active here. (I've been away for the better part of a month.)
My vote is to merge this PR, before it gets any bigger, if that's cool with you @oOCKYOo

**Comment by oOCKYOo** [comment]
Sure, thats probably best instead of trying to fragment it into different PR's

**Pull request merged**
